#!/bin/env python3

import argparse
import os
import glob
import gzip
import matplotlib.pyplot as plt
from  collections import defaultdict

def get_arguments() -> tuple[str, str]:
    """get the arguments"""

    d = "script to draw histograms of segmental duplication counts from synolog"

    parser = argparse.ArgumentParser(description = d)
    parser.add_argument("-d", "--dirc", help="directory containing *-SegmentalDuplications.tsv files from `synolog`", required=True)
    parser.add_argument("-o", "--orgs", help="org_list.tsv generated by synolog", required=True)
    args = parser.parse_args()
    dirc = args.dirc
    orgs  = args.orgs

    assert os.path.isdir(dirc), f"Could not locate directory {dirc}"
    assert os.path.isfile(orgs), f"Could not locate {orgs}"

    return (dirc, orgs)

def get_tsvs(dirc: str) -> list:
    """get the segmental dups files for the target spp"""

    segFiles = list()

    if (dirc[-1] == '/'):
        segFiles = glob.glob(f"{dirc}*_segmentalduplcations.tsv")
    else:
        segFiles = glob.glob(f"{dirc}/*_segmentalduplcations.tsv")

    assert len(segFiles) > 0, f"Could not locate any *-_segmentalduplcations.tsv files at {dirc}"

    return segFiles

def read_orgs(orgs: str) -> dict[str, int]:
    """return a dict of the row/column index each org will be assigned to"""

    orgIdx = dict()

    fh = open(orgs, 'r')
    i  = 0

    for line in fh:
        if (len(line) == 0 or line[0] == '#'):
            continue
        org         = line.strip()
        orgIdx[org] = i
        i += 1

    fh.close()

    return orgIdx

def make_array(freqDict: dict, vals: list) -> None:
    """place the frequencies & sizes into a 2D array"""

    for size, freq in freqDict.items():
        vals[0].append(size)
        vals[1].append(freq)

def get_org_names(segFile: str) -> tuple[str, str]:
    """return the names of the two orgs"""

    bname  = os.path.basename(segFile)
    bname  = bname.replace("_segmentalduplcations.tsv", '')
    fields = bname.split('-')

    return (fields[0], fields[1])


def read_segFile(segFile: str, orgA: str, orgB: str, freqDictA: dict[int:int], freqDictB: dict[int:int]) -> None:
    """fill the dict with the size of each segmental duplication"""

    fh   = gzip.open(read_segFile, "rt") if segFile.startswith(".gz") else open(segFile, 'r')
    prev = '-1'

    for line in fh:
        if (line[0] == '#'): continue
        fields = line.split('\t')
        if (fields[0] == prev): continue
        if (fields[2] == orgA):
            freqDictA[int(fields[1])] += 1
        elif (fields[2] == orgB):
            freqDictB[int(fields[1])] += 1
        prev = fields[0]

    fh.close()


def plot_seg(dirc: str, orgIdx: dict[str, int]) -> None:
    """loop through and plot the figures"""

    N = len(orgIdx)

    fig, axes = plt.subplots(nrows=N, ncols=N, figsize=(12, 10))
    segFiles  = get_tsvs(dirc)

    print(orgIdx)

    for segFile in segFiles:
        freqDictA  = defaultdict(int)
        freqDictB  = defaultdict(int)
        orgA, orgB = get_org_names(segFile)
        # fill the two counts
        read_segFile(segFile, orgA, orgB, freqDictA, freqDictB)
        
        # get assigned row & columns
        r = orgIdx[orgA]
        c = orgIdx[orgB]

        # create a 2D array with the values
        vals = [[], []] # x- & y-vals

        # now A to B
        make_array(freqDictA, vals)
        n = sum(vals[1])
        if (r == N - 1):
            axes[r, c].set_xlabel("Size", fontsize=14)
        if (c == 0):
            axes[r, c].set_ylabel("Frequency", fontsize=14)
        axes[r, c].bar(vals[0], vals[1], width=1.0, color="#008B8B", edgecolor="black")
        axes[r, c].set_ylim(0)
        axes[r, c].text(0.95, 0.95, f"n = {n}", ha="right", va="top", transform=axes[r,c].transAxes, fontsize = 14)

        # now B to A
        vals = [[], []]
        r, c = c, r # swap

        # now A to B
        make_array(freqDictB, vals)
        n = sum(vals[1])
        if (r == N - 1):
            axes[r, c].set_xlabel("Size", fontsize=14)
        if (c == 0):
            axes[r, c].set_ylabel("Frequency", fontsize=14)
        axes[r, c].bar(vals[0], vals[1], width=1.0, color="#008B8B", edgecolor="black")
        axes[r, c].set_ylim(0)
        axes[r, c].text(0.95, 0.95, f"n = {n}", ha="right", va="top", transform=axes[r,c].transAxes, fontsize = 14)

    #
    # add axis titles to first & last subfigs
    #
    axes[0, 0].set_ylabel("Frequency", fontsize=14)
    axes[N - 1, N - 1].set_xlabel("Size", fontsize=14)

    plt.subplots_adjust(wspace=0.3, hspace=0.3)
    plt.savefig(f"SegDups.png")


def main() -> int:
    """entry point to this little subprogram"""

    # get arguments
    dirc, orgs = get_arguments()

    # get the dict of orgs
    orgIdx = read_orgs(orgs)

    # now plot everything
    plot_seg(dirc, orgIdx)

    return 0

if __name__ == "__main__":
    main()
